// Model behind the Combined page: the arm + adapter + LEAP hand as one articulated tree.
//
// The combined URDF (generated by `uv run clankers-build-urdf`) names its joints exactly as
// robots.yaml does — joint1..joint6 for the arm, semantic names for the 16 hand joints — so a
// single flat { jointName: radians } map drives the whole viewer. That is why this file can
// build targets without knowing anything about the URDF itself.

import { buildHandModel, clampToLimit } from './leapHand';

export const ARM_JOINT_COUNT = 6;

function toFiniteNumber(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

// The arm's 7th entry is the parallel gripper, which is not a revolute arm joint and is
// driven separately (gripper_joint1/2 in the URDF), so it is excluded here.
export function buildArmJoints(robotsConfig) {
  const joints = robotsConfig?.arm?.joints;
  if (!Array.isArray(joints)) {
    throw new Error('robotsConfig.arm.joints is missing — regenerate with clankers-export-config');
  }
  return joints
    .filter((j) => Number(j.joint) <= ARM_JOINT_COUNT)
    .map((j) => ({
      name: String(j.name),
      joint: Number(j.joint),
      motorId: toFiniteNumber(j.motor_id),
      model: j.model ?? null,
      limit: {
        min: toFiniteNumber(j.limit?.min) ?? -Math.PI,
        max: toFiniteNumber(j.limit?.max) ?? Math.PI,
      },
    }));
}

export function buildCombinedModel(robotsConfig) {
  const adapter = robotsConfig?.adapter || null;
  return {
    arm: buildArmJoints(robotsConfig),
    hand: buildHandModel(robotsConfig),
    // `calibrated: false` on either side means the pose on screen is a drawing, not a
    // measurement — the page says so rather than quietly implying the model is trustworthy.
    adapterCalibrated: Boolean(adapter?.calibrated),
    adapterMesh: adapter?.mesh ?? null,
  };
}

export function clampArmJoint(joint, valueRad) {
  const n = Number(valueRad);
  if (!Number.isFinite(n)) return 0;
  return Math.min(joint.limit.max, Math.max(joint.limit.min, n));
}

/** Every joint at zero, clamped into its own limits — the neutral pose for the viewer. */
export function zeroTargets(model) {
  const out = {};
  for (const j of model.arm) out[j.name] = clampArmJoint(j, 0);
  for (const j of model.hand.joints) out[j.name] = clampToLimit(j, 0);
  return out;
}

/** Merge live gateway joint readings (servo_id keyed) into a name-keyed target map. */
export function applyLiveHandPositions(targets, model, liveJoints) {
  if (!Array.isArray(liveJoints) || liveJoints.length === 0) return targets;
  const next = { ...targets };
  for (const live of liveJoints) {
    const joint = model.hand.byServoId.get(Number(live?.servo_id));
    const pos = Number(live?.pos);
    if (joint && Number.isFinite(pos)) next[joint.name] = clampToLimit(joint, pos);
  }
  return next;
}
